MAIN_PINK = '#dcc2fe'
MAIN_BLUE = '#5fadfb'
MAIN_PURPLE = '#615efa'
RED = '#E73E3A'
DARK_RED = '#8a3b3a'
LIME_GREEN = '#4DD753'
DARK_GREEN = '#265d29'
YELLOW_LIME = '#b9fd00'
ORANGE = '#E75826'
LIGHT_ORANGE = '#e3a68c'
SKY_BLUE = '#06AED5'
LIGHT_SKY_BLUE = '#92c4da'
WHITE = '#FFFFFF'
BLACK = '#000000'
GREY = '#707070'

# CHART
BACKGROUND = WHITE
BULLISH_CANDLE_OUTLINE = SKY_BLUE
BULLISH_CANDLE_FILL = BACKGROUND
BEARISH_CANDLE_OUTLINE = ORANGE
BEARISH_CANDLE_FILL = BACKGROUND
INDICATOR_LINE = MAIN_PURPLE